### ISSUE TITLE
Failed to load a language-glsl package grammar

### ISSUE THREAD

**Issue by dmnz** [hughsk/language-glsl#25]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-glsl](https://github.com/hughsk/language-glsl) package 2.0.4

### Stack Trace

Failed to load a language-glsl package grammar

```
At atom.grammars.startIdForScope is not a function in C:\Users\Dan\.atom\packages\language-glsl\grammars\glsl.cson

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/first-mate/lib/grammar-registry.js:80:26)
    at Grammar.module.exports.Grammar.activate (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/first-mate/lib/grammar.js:259:54)
    at grammarRegistry.readGrammar (~/AppData/Local/atom/app-1.28.2/resources/app/src/package.js:617:53)
    at CSON.readFile (~/AppData/Local/atom/app-1.28.2/resources/app/src/grammar-registry.js:476:15)
    at parseContents (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/season/lib/cson.js:123:13)
    at ~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/season/lib/cson.js:226:30
    at FSReqWrap.oncomplete (fs.js:152:21)
  at /packages/language-glsl/grammars/glsl.cson:1:1
```

### Commands

```
  5x -3:35.3.0 core:backspace (input.hidden-input)
  2x -2:08.3.0 editor:move-to-first-character-of-line (input.hidden-input)
 26x -2:07.9.0 core:page-up (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-glsl 0.2.3 
autocomplete-love 0.4.0 
busy-signal 1.4.3 
hyperclick 0.1.5 
hyperclick-love 0.6.0 
intentions 1.1.5 
language-glsl 2.0.4 
language-lua 0.9.11 
linter 2.2.0 
linter-luaparse 0.2.0 
linter-ui-default 1.7.1 
love-ide 0.17.0 
omnisharp-atom 0.31.2 
tool-bar 1.1.7 
```

**Comment by fordhurley** [comment]
Strange how atom shows this as being thrown by language-glsl, when it appears to be coming from omnisharp-atom. See https://github.com/OmniSharp/omnisharp-atom/issues/1020, https://github.com/OmniSharp/omnisharp-atom/issues/1023, and https://github.com/OmniSharp/omnisharp-atom/issues/1027

Would you mind disabling the omnisharp-atom package and trying again?
