### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by nnorm** [hughsk/language-glsl#9]
[Enter steps to reproduce below:]

1. open a random php document
2. select both a comment and some php code

**Atom Version**: 1.3.2
**System**: Windows 8.1 x64 Professionnal Version
**Thrown From**: [language-glsl](https://github.com/hughsk/language-glsl) package, v2.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /C:/Users/nnorm/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:607

TypeError: Cannot read property 'indexOf' of undefined
    at Object.module.exports.getMemberContext (file:///C:/Users/nnorm/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:682:25)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (C:\Users\nnorm\.atom\packages\atom-autocomplete-php\lib\tooltip\function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (C:\Users\nnorm\.atom\packages\atom-autocomplete-php\lib\tooltip\abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (C:\Users\nnorm\.atom\packages\atom-autocomplete-php\lib\tooltip\abstract-provider.coffee:78:22)
    at HTMLDivElement.jQuery.event.dispatch (C:\Users\nnorm\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\nnorm\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -7:37.6.0 core:save (atom-text-editor.editor.is-focused)
     -7:05.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -7:04.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -5:18.2.0 core:delete (atom-text-editor.editor.is-focused)
     -5:15.4.0 core:save (atom-text-editor.editor.is-focused)
     -5:06.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -5:04.2.0 core:save (atom-text-editor.editor.is-focused)
  5x -4:16.4.0 core:close (atom-text-editor.editor.is-focused)
     -3:38 core:copy (atom-text-editor.editor.is-focused)
  8x -3:37.2.0 core:paste (atom-text-editor.editor.is-focused)
  2x -3:32.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:37.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:37.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:31.8.0 core:undo (atom-text-editor.editor.is-focused)
     -2:31.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:29.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.4
color-picker, v2.0.14
language-glsl, v2.0.1
language-x86asm, v0.7.1
minimap, v4.19.0

# Dev
No dev packages
```

**Comment by hughsk** [comment]
@nnorm this error is coming from atom-autocomplete-php, I'm not sure why it's reporting that it's from language-glsl! Closing :)
